# Generated by Django 6.1 on 2026-08-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workrecord',
            options={'ordering': ['-work_date']},
        ),
        migrations.AddField(
            model_name='workrecord',
            name='status',
            field=models.CharField(choices=[('WORKED', 'Worked'), ('ABSENT', 'Absent'), ('OFF', 'Off Day'), ('LEAVE', 'Leave')], default='WORKED', max_length=20),
        ),
    ]
